let shop = [
  {
    category: "Mens",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,
            brand: "Dior",
            color: "Blue",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/men_tops/top_1_front.png",
            description:
              "Comfortable and stylish Nike men's top with moisture-wicking fabric.",
          },
          {
            id: 1,
            brand: "Adidas",
            color: "Khaki Brown",
            size: "Small, Medium, Large",
            price: "₱449.99",
            image: "img/men_tops/top_2_front.png",
            description:
              " Crafted with quality and comfort in mind, this top is a ensuring a perfect fit for every individual. The versatile khaki brown color adds a touch of sophistication to your wardrobe.",
          },
          {
            id: 2,
            brand: "Nike",
            color: "Dirty White",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/men_tops/top_3_front.png",
            description:
              "Breathable Puma men's top suitable for workouts and casual wear.",
          },
          {
            id: 3,
            brand: "Dickies",
            color: "White and Pink",
            size: "Small, Medium, Large",
            price: "₱549.99",
            image: "img/men_tops/top_4_front.png",
            description:
              "Whether you're aiming for a laid-back look or want to make a statement, this top has got you covered. The classic combination of white and pink adds a touch of freshness to your outfit.",
          },
          {
            id: 4,
            brand: "Reebok",
            color: "Black, Brown, White ",
            size: "Medium, Large, XL",
            price: "₱479.99",
            image: "img/men_tops/top_5_front.png",
            description:
              "Classic Reebok men's top with a modern twist, perfect for everyday wear.",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,
            brand: "Lee",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱249.99",
            image: "img/men_bottom/bottom_1_front.png",
            description: "Comfortable but stylish mens shorts.",
          },
          {
            id: 1,
            brand: "Nike",
            color: "Black and Brown",
            size: "Medium, Large, XL",
            price: "₱399.99",
            image: "img/men_bottom/bottom_2_front.png",
            description:
              "Crafted for those who demand both style and functionality, these shorts are ideal for workouts, casual outings, or just relaxing at home.",
          },
          {
            id: 2,
            brand: "Puma",
            color: "White",
            size: "Small, Large, XL",
            price: "₱369.99",
            image: "img/men_bottom/bottom_3_front.png",
            description: "White pants with 6 pockets",
          },
          {
            id: 3,
            brand: "Under Armour",
            color: "Gray Heather",
            size: "Small, Medium, Large",
            price: "₱749.99",
            image: "img/men_bottom/bottom_4_front.png",
            description:
              "High-performance Under Armour men's pants with quick-dry technology.",
          },

          {
            id: 4,
            brand: "Under Armour",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱729.99",
            image: "img/men_bottom/bottom_5_front.png",
            description: "Leather jogger pants with 6 pockets.",
          },
        ],
      },
      {
        type: "Sweater",
        classification: [
          {
            id: 0,
            brand: "Nike",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_1_front.png",
            description: "A stylish sweater wit a comfortable fabric.",
          },
          {
            id: 1,
            brand: "Lacoste",
            color: "Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_2_front.png",
            description: "A printed cotton sweater.",
          },
          {
            id: 2,
            brand: "Adidas",
            color: "Green",
            size: "Small, Medium, Large",
            price: "₱589.99",
            image: "img/men_sweater/sweater_3_front.png",
            description:
              " A perfect fusion of style and comfort. Elevate your casual wardrobe with this versatile piece that adds a pop of color to your ensemble. ",
          },
          {
            id: 3,
            brand: "Nike",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_4_front.png",
            description:
              "A timeless addition to your cold-weather collection. Crafted with precision and style, this knitted sweater not only keeps you warm but also ensures you stay on-trend.",
          },
          {
            id: 4,
            brand: "Nike",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/men_sweater/sweater_5_front.png",
            description:
              "The perfect blend of comfort and urban style. This classic black hoodie is a wardrobe essential, providing warmth and a contemporary edge to your look.",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "H&M",
            color: "White & Blue",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/men_co-ords/co-ords_1_front.png",
            description:
              "This set includes a pair of stylish shorts and a matching t-shirt, making it an effortless choice for beach days, or just relaxing at home.",
          },
          {
            id: 1,
            brand: "Lee",
            color: "Black & Brown",
            size: "Small, Medium, Large",
            price: "₱699.99",
            image: "img/men_co-ords/co-ords_2_front.png",
            description:
              "This pair features a classic t-shirt and comfortable shorts, resulting in a coordinated and effortlessly chic style.",
          },
          {
            id: 2,
            brand: "Penshoppe",
            color: "Black and Cream",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/men_co-ords/co-ords_3_front.png",
            description:
              " This set includes uniquely designed printed shorts and pants, adding an extra layer of personality to your look.",
          },
          {
            id: 3,
            brand: "Uniqlo",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/men_co-ords/co-ords_4_front.png",
            description:
              "Crafted from high-quality materials, this co-ords set ensures a comfortable and relaxed fit, making it ideal for both lounging and casual outings.",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Black and White",
            size: "Small, Medium, Large",
            price: "₱959.99",
            image: "img/men_co-ords/co-ords_5_front.png",
            description:
              "A perfect fusion of athletic flair and contemporary style. This set features a baseball-inspired design, including a comfortable top and matching bottoms. ",
          },
        ],
      },
    ],
  },
  {
    category: "Women",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,
            brand: "Chanel",
            color: "Cornflower Blue",
            size: "Small, Medium, Large",
            price: "₱1,599.00",
            image: "img/women_tops/tops_1_front.png",
            description: "Floral crop top with puff sleaves.",
          },
          {
            id: 1,
            brand: "Dior",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱1,499.00",
            image: "img/women_tops/tops_2_front.png",
            description: "Big Bow Back Ruffle Hem Cami Top.",
          },
          {
            id: 2,
            brand: "Zara",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/women_tops/tops_3_front.png",
            description: "Long sleeve crop top.",
          },
          {
            id: 3,
            brand: "Zaful",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱999.00",
            image: "img/women_tops/tops_4_front.png",
            description:
              " A perfect blend of fashion and femininity. This top features a chic checkered pattern, long sleeves, and an off-shoulder design, making it a versatile choice for various occasions.",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/women_tops/tops_2_front.png",
            description:
              "The deep navy blue color offers a timeless and flexible touch to any ensemble. Designed from high-quality materials, this Zalora blouse has a flattering fit and flows wonderfully on the body..",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,
            brand: "Zalora",
            color: "Black",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/women_bottom/bottom_3_front.png",
            description: "Balck offive pants.",
          },
        ],
      },
      {
        type: "Skirt",
        classification: [
          {
            id: 0,
            brand: "H&M",
            color: "Pearl white",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/women_bottom/bottom_1_front.png",
            description:
              "This skirt is designed to perfectly combine fashion and function, giving you the confidence to conquer any exercise or casual outing.",
          },
          {
            id: 1,
            brand: "Uniqlo",
            color: "Peach",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/women_bottom/bottom-2_front.png",
            description: "Flowery pattern skirt perfect for beach outfits.",
          },
          {
            id: 2,
            brand: "Penshoppe",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱1,099.00",
            image: "img/women_bottom/bottom_5_front.png",
            description: "White skirt with ribbon .",
          },
          {
            id: 3,
            brand: "Geuss",
            color: "Cream",
            size: "Small, Medium, Large",
            price: "₱849.00",
            image: "img/women_bottom/bottom_4_front.png",
            description: "Fitted short skirt with slit design.",
          },
        ],
      },
      {
        type: "Dress",
        classification: [
          {
            id: 0,
            brand: "Shein",
            color: "Baby Blue",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/blue_short_dress_front.png",
            description: "Jacquard Square Neck Puff Sleeve Dress.",
          },
          {
            id: 1,
            brand: "Zalora",
            color: "Olive Green",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_dress/long_dress_green_front.png",
            description: "Solid Tie Shoulder Cami Dress",
          },
          {
            id: 2,
            brand: "Zaful",
            color: "Salmon Pink",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_dress/pink_dress_front.png",
            description: " Floral Print Cami Dress Without Blouse",
          },
          {
            id: 3,
            brand: "Penshoppe",
            color: "Carnation Pink",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/pink_floral_dress_front.png",
            description: "Allover Floral Print Ruched Bust Cami Dress.",
          },
          {
            id: 4,
            brand: "Zalora",
            color: "Silver",
            size: "Small, Medium, Large",
            price: "₱799.99",
            image: "img/women_dress/sexy_grey_dress_front.png",
            description: " Crisscross Backless Ruched Glitter Bodycon Dress.",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "Zalora",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱1,099.00",
            image: "img/women_co-ords/co-ords_1_front.png",
            description: "Contrast Trim Bow Front Crop Jacket & Skirt.",
          },
          {
            id: 1,
            brand: "Zara",
            color: "White and Green",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/women_co-ords/co-ords_2_front.png",
            description: " Solid Crop Top & Ditsy Floral Print Wrap Skirt Set.",
          },
          {
            id: 2,
            brand: "H&M",
            color: "Peral White",
            size: "Small, Medium, Large",
            price: "₱1,099.99",
            image: "img/women_co-ords/co-ords_3_front.png",
            description:
              "Ladies' Lace Camisole Top And Mermaid Hem Skirt Two Piece Set.",
          },
          {
            id: 3,
            brand: "Penshoppe",
            color: "Almond",
            size: "Small, Medium, Large",
            price: "₱899.99",
            image: "img/women_co-ords/co-ords_4_front.png",
            description:
              "Knitted Diamond Checkered Printed Tank Top And Pleated Skirt Set",
          },
          {
            id: 4,
            brand: "Bench",
            color: "Onyx Black",
            size: "Small, Medium, Large",
            price: "₱999.99",
            image: "img/women_co-ords/co-ords_5_front.png",
            description:
              " Ladies' Solid Color Faux Leather Strapless Two Piece Set.",
          },
        ],
      },
    ],
  },
  {
    category: "Kids",
    items: [
      {
        type: "Tops",
        classification: [
          {
            id: 0,
            brand: "Bench",
            color: "White and Black",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_1_front.png",
            description: "inside shirt white and sando infront",
          },
          {
            id: 1,
            brand: "H&M",
            color: "White",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_tops/top_2_front.png",
            description: "Crop top polo ",
          },
          {
            id: 2,
            brand: "Hello Kitty",
            color: "White, Gray and Black",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_3_front.png",
            description: ".Letter Graphic Tee",
          },
          {
            id: 3,
            brand: "Hello Kitty",
            color: "Baby Powder White",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/kids_tops/top_4_front.png",
            description: "Knitted Solid Off Shoulder Slim Fit Casual T-Shirt.",
          },
          {
            id: 4,
            brand: "Old Navy",
            color: "Pink",
            size: "Small, Medium, Large",
            price: "₱399.99",
            image: "img/kids_tops/top_5_front.png",
            description: "Maong shorts with pink heart tshirt. ",
          },
        ],
      },
      {
        type: "Pants",
        classification: [
          {
            id: 0,
            brand: "Old Navy",
            color: "Copper Brown",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_4_front.png",
            description: "Straight leg pants.",
          },
          {
            id: 1,
            brand: "H&M",
            color: "Camel Brown",
            size: "Small, Medium, Large",
            price: "₱459.99",
            image: "img/kids_bottom/bottom_5_front.png",
            description: "Jogger pants with six pockets.",
          },
        ],
      },
      {
        type: "Shorts",
        classification: [
          {
            id: 0,
            brand: "Penshoppe",
            color: "Baby Blue",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_1_front.png",
            description: "Striped Print Bow Front Asymmetrical Hem Skort.",
          },
          {
            id: 2,
            brand: "Old Navy",
            color: "Copper Brown",
            size: "Small, Medium, Large",
            price: "₱599.99",
            image: "img/kids_bottom/bottom_2_front.png",
            description:
              "Fashionable And Elegant Plaid Woven Shorts With Metal Decorated Button.",
          },
          {
            id: 3,
            brand: "Zara",
            color: "Midnight Black",
            size: "Small, Medium, Large",
            price: "₱499.99",
            image: "img/kids_bottom/bottom_3_front.png",
            description:
              "Solid Color Paper Bag Tie Waist Bowknot Skort For Summer.",
          },
        ],
      },
      {
        type: "Dress",
        classification: [
          {
            id: 0,
            brand: "Penshoppe",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/kids_dress/dress_1_front.png",
            description:
              "Preppy-Style Heart-Shaped Printed Striped Polo Collar Sleeveless Dress, Summer.",
          },
          {
            id: 1,
            brand: "Bench",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱659.00",
            image: "img/kids_dress/dress_2_front.png",
            description:
              "Unleash the trendsetter in your little one with Bench's navy blue wonder. This dress combines fashion and functionality seamlessly. With sizes ranging from Small to Large, it's a perfect fit for any adventure.",
          },
          {
            id: 2,
            brand: "Shein",
            color: "Cedar Brown",
            size: "Small, Medium, Large",
            price: "₱699.00",
            image: "img/kids_dress/dress_3_front.png",
            description:
              "Embrace elegance with Shein's Cedar Brown dress, a sophisticated addition to your kid's wardrobe. This dress is a blend of comfort and chic.",
          },
          {
            id: 3,
            brand: "Zara",
            color: "Periwinkle Purple",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_dress/dress_4_front.png",
            description:
              "Everyday Casual Knitted Solid Color round-Neck Short Sleeve Dress",
          },
          {
            id: 4,
            brand: "H&M",
            color: "Brink Pink",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_dress/dress_5_front.png",
            description:
              "Double-Layered Floral Printed Party Cami Dress With Bow Tie And Frilly Hem For Summer",
          },
        ],
      },
      {
        type: "Co-ords",
        classification: [
          {
            id: 0,
            brand: "Shein",
            color: "Taupe Brown",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ords_1_front.png",
            description:
              "Letter Graphic Striped Trim Sweater & Pleated Knit Skirt",
          },
          {
            id: 1,
            brand: "Zalora",
            color: "Navy Blue",
            size: "Small, Medium, Large",
            price: "₱899.00",
            image: "img/kids_co-ords/co-ords_2_front.png",
            description:
              "Flower Decorated Knitted Cardigan And Pleated Skirt Set",
          },
          {
            id: 2,
            brand: "Zara",
            color: "Camel Brown, Black",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ords_3_front.png",
            description:
              "Ruffle Trim Cable Knit Cardigan & Plaid Pattern Knit Skirt",
          },
          {
            id: 3,
            brand: "Old Navy",
            color: "Ginger Brown",
            size: "Small, Medium, Large",
            price: "₱799.00",
            image: "img/kids_co-ords/co-ords_4_front.png",
            description: "Kbitted kids beach wear.",
          },
          {
            id: 4,
            brand: "Zara",
            color: "Dark Brown",
            size: "Small, Medium, Large",
            price: "₱599.00",
            image: "img/kids_co-ords/co-ords_4_front.png",
            description: "Checkered sweater set",
          },
        ],
      },
    ],
  },
];

module.exports = { shop };
